[window]
opacity=1.0

[font]
normal.family = "Iosevka"
size = 11

# no-clown-fiesta theme
# [colors.primary]
# background = "#151515"  # bg from Lua
# foreground = "#E1E1E1"  # fg from Lua
# dim_foreground = "#727272"  # medium_gray from Lua
#
# [colors.cursor]
# text = "#151515"        # cursor_fg from Lua
# cursor = "#D0D0D0"      # cursor_bg from Lua
#
# [colors.normal]
# black = "#373737"       # gray from Lua
# red = "#b46958"         # red from Lua
# green = "#90A959"       # green from Lua
# yellow = "#F4BF75"      # yellow from Lua
# blue = "#BAD7FF"        # blue from Lua
# magenta = "#AA759F"     # magenta from Lua
# cyan = "#88afa2"        # cyan from Lua
# white = "#E1E1E1"       # white from Lua
#
# [colors.bright]
# black = "#727272"       # medium_gray from Lua
# red = "#b46958"         # red from Lua (no bright variant provided)
# green = "#90A959"       # green from Lua (no bright variant provided)
# yellow = "#F4BF75"      # yellow from Lua (no bright variant provided)
# blue = "#BAD7FF"        # blue from Lua (no bright variant provided)
# magenta = "#AA759F"     # magenta from Lua (no bright variant provided)
# cyan = "#88afa2"        # cyan from Lua (no bright variant provided)
# white = "#AFAFAF"       # light_gray from Lua
#
# [colors.dim]
# black = "#373737"       # gray from Lua
# red = "#b46958"         # red from Lua (no dim variant provided)
# green = "#90A959"       # green from Lua (no dim variant provided)
# yellow = "#F4BF75"      # yellow from Lua (no dim variant provided)
# blue = "#BAD7FF"        # blue from Lua (no dim variant provided)
# magenta = "#AA759F"     # magenta from Lua (no dim variant provided)
# cyan = "#88afa2"        # cyan from Lua (no dim variant provided)
# white = "#727272"       # medium_gray from Lua
#
# [[colors.indexed_colors]]
# index = 16
# color = "#FFA557"       # orange from Lua
#
# [[colors.indexed_colors]]
# index = 17
# color = "#AA749F"       # purple from Lua

# catpuccin mocha theme colors
[colors.primary]
background = '#1E1E2E' # base
foreground = '#CDD6F4' # text
# Bright and dim foreground colors
dim_foreground = '#CDD6F4' # text
bright_foreground = '#CDD6F4' # text

# Cursor colors
[colors.cursor]
text = '#1E1E2E' # base
cursor = '#F5E0DC' # rosewater

[colors.vi_mode_cursor]
text = '#1E1E2E' # base
cursor = '#B4BEFE' # lavender

# Search colors
[colors.search.matches]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.search.focused_match]
foreground = '#1E1E2E' # base
background = '#A6E3A1' # green

[colors.footer_bar]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#1E1E2E' # base
background = '#F9E2AF' # yellow

[colors.hints.end]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

# Selection colors
[colors.selection]
text = '#1E1E2E' # base
background = '#F5E0DC' # rosewater

# Normal colors
[colors.normal]
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1

# Bright colors
[colors.bright]
black = '#585B70' # surface2
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#A6ADC8' # subtext0

# Dim colors
[colors.dim]
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1
