# ~/.zshenv
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$HOME/.cargo/bin:$PATH
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/opt/texlive2026/bin/x86_64-linux

export MANPATH=$MANPATH:/opt/texlive2026/tex-mf/doc/man
export MANPATH=$MANPATH:$HOME/.local/gh_2.96.0_linux_amd64/share/man/

export DOWNLOADS=$HOME/Downloads
export CODE="/mnt/code"
export COURSES="/mnt/courses"
export DATA="/mnt/data"

export PHD=/home/danjd/projects/phd-completion
export TODAY=$(date --iso-8601)

alias glu="git lu"
alias gca="git ca"
alias gst="git st"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias la='ls -A'
alias l="ls -alF --color=auto"

# Needed to avoid warnings with compinit
#   https://github.com/zimfw/zimfw/wiki/Troubleshooting#completion-is-not-working
skip_global_compinit=1
